### ISSUE TITLE
Recommendations by category doesn't work

### ISSUE THREAD

**Issue by EduardSelles** [EmicoEcommerce/Magento1Tweakwise#2]
Steps to reproduce
--
1. Check Emico demo environment, product detail page:
https://tweakwise1-ce.emico.nl/aviator-sunglasses.html

2. Check Magento Admin > Catalog > Manage Categories
category: Default Category (UK > Accessoires > Eyeware, tab 'Tweakwise'

Actual result
-- Detail page without recommendations

Expected result
--  Detail page including recommendations

![untitled-2](https://user-images.githubusercontent.com/26865971/36905800-90d282b0-1e34-11e8-92e9-50be943c1939.png)

**Comment by Fgruntjes** [comment]
Hello,

This is due to the fact that magento does not register the product under the category when you just search for the product. When you browse to the product using the category tree you will get the expected result.

Please see my demo: 
![nimbus-record-video-2018-03-06-14-33-43](https://user-images.githubusercontent.com/984466/37035064-928ef16e-214b-11e8-88e9-1752748c6fa4.gif)

This is default Magento behavior, however we are aware that most shops would prefer that all routes to a product produce the same result. The problem with a generic implementation here is that not all shops have all products under 1 categorie. So there is no true silver bullet here.

A shop however can set the Magento registry key `current_category` when this is not set already. But offcourse this also has influence on the breadcrumbs etc.

What we suggest doing is to add an observer to the `catalog_controller_product_init_after` event. Like so:
```xml
<?xml version="1.0"?>
<config>
    <frontend>
        <events>
            <catalog_controller_product_init_after>
                <observers>
                    <shoeby_layout>
                        <class>your_module/observer</class>
                        <method>setDefaultCategory</method>
                    </shoeby_layout>
                </observers>
            </catalog_controller_product_init_after>
        </events>
    </frontend>
</config>
```

```php
<?php

class Your_Module_Model_Observer
{
    /**
     * Set current category if not set
     *
     * @param Varien_Event_Observer $event
     */
    public function setDefaultCategory(Varien_Event_Observer $event)
    {
        if (Mage::registry('current_category')) {
            return;
        }

        /** @var Mage_Catalog_Model_Product $product */
        $product = $event->getData('product');

        $categories = $product->getCategoryIds();
        if (count($categories) == 0) {
            return;
        }

        $categoryId = reset($categories);
        $category = Mage::getModel('catalog/category');
        $category->load($categoryId);
        
        Mage::register('current_category', $category);
    }
}
```

**Comment by ArjenMiedema** [comment]
@Fgruntjes I have this issue as well for a client. I checked the steps you mentioned, but even when I go to a category page and then select a product, I don't get any related products. When I disable the template on category level (so it falls back to default), it does show product. But now I get a pillow cover as a related product for a set of knives.

So the issue isn't just happening for products after searching, but also for products that you click from the category view. Can you please review this? 

If you want more info about this case, please give me a way to contact you directly (i.e. mail).

**Comment by bertterheide** [comment]
@EduardSelles, @Fgruntjes this issue is still relevant. A client called us explaining that they wanted to set a default upsell template for a category, but this template was not showing up on the product page. 

After some digging, I found out that the source model that is configured for the tweakwise_upsell_template category attribute (emico_tweakwise/system_config_source_recommendationFeatured) differs from the tweakwise_upsell_template product attribute (emico_tweakwise/system_config_source_recommendationProduct).

This is incorrect, and the source model for the category attribute should be emico_tweakwise/system_config_source_recommendationProduct.

Could you please fix this?

**Comment by ArjenMiedema** [comment]
@bertterheide I already created [a pull request](https://github.com/EmicoEcommerce/Magento1Tweakwise/pull/25) for this about a week ago. For the time being we introduced an addon for this with only this fix in it. That solved it for us.
