### ISSUE TITLE
The layered navigation ajax template is still parsed when Tweakwise layered navigation is disabled

### ISSUE THREAD

**Issue by pimdebrabander** [EmicoEcommerce/Magento1Tweakwise#22]
Issue Brief
--
The layered navigation ajax template is still parsed when "Tweakwise > Layered navigation > Ajax enabled" is true and "Tweakwise > Layered navigation > Enabled" is false in "System > Configuration > Tweakwise". When you disable the layered navigation option, the ajax option gets hidden because its dependent upon it. But the option might still be enabled in the database. Also the xml injection only checks if ajax is enabled or disabled.

Environment
--
- [ ] Tweakwise Version: 1.11.5
- [ ] Magento Version: 1.9.3.9
- [ ] Magento Enterprise: no

Steps to reproduce
--
1. Set "System > Configuration > Tweakwise > Layered navigation > Enabled" to true
2. Set "System > Configuration > Tweakwise > Layered navigation > Ajax enabled" to true
3. Save.
4. Set "System > Configuration > Tweakwise > Layered navigation > Enabled" to false
5. Save

Actual result
--
1. The page still renders "emico_tweakwise/catalog/layer/ajax.phtml".

Expected result
--
- [ ] The page should not render the file because Tweakwise Layered Navigation is disabled.

**Comment by edwinljacobs** [comment]
This has been fixed and will be released soon.

**Comment by edwinljacobs** [comment]
Sorry for the confusion but I came to the conclusion that this has not been fixed. Also this isn't that easy. The block is included in layout based on the condition that ajax navigation is enabled in config. The way magento config works is that if you disable navigation then the ajax navigation field disappears since it is a dependency. When you save the value is not updated and it will remain whatever it was. You need to manually disable ajax navigation and then navigation. Since this the way magento works we will not fix this issue. If you know a good solution in layout then please let us know preferably via a merge request and we will consider the solution.
